import 'package:booking_app/constants/app_const.dart';
import 'package:booking_app/constants/img_api.dart';

class City {
  final String id;
  final String code;
  final String name;
  final String country;
  final String description;
  final List<String> photos;
  final double totalHotel;
  final double totalHomestay;
  final double totalWorkspace;

  City({
    required this.id,
    required this.code,
    required this.name,
    required this.country,
    required this.description,
    required this.photos,
    required this.totalHotel,
    this.totalHomestay = 0,
    this.totalWorkspace = 0,
  });
}

final List<City> cityList = [
  City(
    id: '1',
    code: 'BDG',
    name: 'Bandung',
    country: 'Indonesia',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[151]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '2',
    code: 'LSB',
    name: 'Lisbon',
    country: 'Portugal',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[152]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '3',
    code: 'LDN',
    name: 'London',
    country: 'United Kingdom',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[153]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '4',
    code: 'KLP',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[154]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '5',
    code: 'IST',
    name: 'Istanbul',
    country: 'Turkey',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[155]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '6',
    code: 'NEW',
    name: 'New York',
    country: 'United States',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[156]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '7',
    code: 'DUB',
    name: 'Dubai',
    country: 'United Arab Emirates',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[157]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '8',
    code: 'CAS',
    name: 'Casablanca',
    country: 'Morocco',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[158]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '9',
    code: 'BEJ',
    name: 'Beijing',
    country: 'China',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[159]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '10',
    code: 'BAL',
    name: 'Bali',
    country: 'Indonesia',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[160]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '11',
    code: 'BNK',
    name: 'Bangkok',
    country: 'Thailand',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[161]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '12',
    code: 'TKY',
    name: 'Tokyo',
    country: 'Japan',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[162]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '13',
    code: 'WAS',
    name: 'Washington',
    country: 'United States',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[163]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '14',
    code: 'BRL',
    name: 'Berlin',
    country: 'Germany',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[164]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '15',
    code: 'SNG',
    name: 'Singapore',
    country: 'Singapore',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[165]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '16',
    code: 'LDN',
    name: 'London',
    country: 'United Kingdom',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[166]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '17',
    code: 'NEW',
    name: 'New York',
    country: 'United States',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[167]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '18',
    code: 'ROM',
    name: 'Rome',
    country: 'Italy',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[168]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '19',
    code: 'WAS',
    name: 'Washington',
    country: 'United States',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[169]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '20',
    code: 'MMB',
    name: 'Mumbai',
    country: 'India',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[170]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '21',
    code: 'NDH',
    name: 'New Delhi',
    country: 'India',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[171]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '22',
    code: 'SEO',
    name: 'Seoul',
    country: 'South Korea',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[172]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '23',
    code: 'SFC',
    name: 'San Francisco',
    country: 'United States',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[173]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '24',
    code: 'NYK',
    name: 'New York',
    country: 'United States',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[174]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '25',
    code: 'MDV',
    name: 'Maldives',
    country: 'Maldives',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[175]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '26',
    code: 'VNC',
    name: 'Venice',
    country: 'Italy',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[176]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '27',
    code: 'MEC',
    name: 'Mecca',
    country: 'Saudi Arabia',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[177]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '28',
    code: 'TKY',
    name: 'Tokyo',
    country: 'Japan',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[178]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '29',
    code: 'BUA',
    name: 'Buenos Aires',
    country: 'Argentina',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[179]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
  City(
    id: '30',
    code: 'BDG',
    name: 'Bandung',
    country: 'Indonesia',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[180]],
    totalHotel: 120,
    totalHomestay: 50,
    totalWorkspace: 30,
  ),
];
