import 'package:booking_app/constants/img_api.dart';
import 'package:booking_app/models/city.dart';

class Homestay {
  final String id;
  final String name;
  final double rating;
  final double reviews;
  final City location;
  final String description;
  final String thumbnail;
  final double price;
  final double discount;
  final List<String>? facilities;
  final String type;
  final String size;
  final int bedRooms;
  final int capacity;

  Homestay({
    required this.id,
    required this.name,
    this.rating = 0,
    this.reviews = 0,
    required this.location,
    required this.description,
    required this.thumbnail,
    required this.price,
    this.discount = 0,
    this.facilities,
    this.type = 'Holiday House',
    this.size = 'medium',
    this.bedRooms = 2,
    this.capacity = 1
  });

  String get formattedPrice => '\$${price.toStringAsFixed(2)}';
  String get formattedDiscount => '\$${discount.toStringAsFixed(2)}';
}

final List<Homestay> homestayList = [
  Homestay(
    id: '1',
    name: 'Azure Haven Homestay',
    rating: 4.5,
    reviews: 120,
    location: cityList[10],
    description: 'Nestled along the pristine coastline, Sunset Tide Resort offers breathtaking ocean views and luxurious amenities perfect for a relaxing escape. Guests',
    thumbnail: ImgApi.photo[51],
    price: 150,
    discount: 30,
    type: 'Apartment',
    capacity: 5,
    facilities: [
      'Free Wi-Fi',
      'Kitchen',
      'Parking',
    ],
  ),
  Homestay(
    id: '2',
    name: 'Urban Business Homestay',
    rating: 4.0,
    reviews: 80,
    location: cityList[11],
    description: 'The Urban Retreat is a contemporary hotel designed for both business and leisure travelers.',
    thumbnail: ImgApi.photo[52],
    price: 220,
    discount: 50,
    capacity: 10,
    facilities: [
      'Free Wi-Fi',
      'Air Conditioning',
      'Free Parking',
    ],
  ),
  Homestay(
    id: '3',
    name: 'Cozy Mountain Retreat',
    rating: 4.8,
    reviews: 200,
    location: cityList[11],
    description: 'Experience the tranquility of the Swiss Alps in this cozy mountain retreat, perfect for nature lovers.',
    thumbnail: ImgApi.photo[53],
    price: 180,
    discount: 15,
    type: 'Villa',
    capacity: 8,
    facilities: [
      'Free Wi-Fi',
      'Kitchen',
      'TV',
      'Air Conditioning',
    ],
  ),
  Homestay(
    id: '4',
    name: 'Charming Countryside Homestay',
    rating: 4.2,
    reviews: 150,
    location: cityList[12],
    description: 'Escape to the picturesque countryside of Tuscany in this charming homestay surrounded by vineyards.',
    thumbnail: ImgApi.photo[54],
    price: 130,
    discount: 8,
    type: 'Villa',
    capacity: 10,
    facilities: [
      'Free Wi-Fi',
      'Kitchen',
    ],
  ),
  Homestay(
    id: '5',
    name: 'Beachfront Paradise Homestay',
    rating: 4.9,
    reviews: 300,
    location: cityList[12],
    description: 'Relax in this beachfront paradise homestay with stunning ocean views and direct beach access.',
    thumbnail: ImgApi.photo[55],
    price: 200,
    discount: 20,
    type: 'Apartment',
    capacity: 6,
    facilities: [
      'Free Wi-Fi',
      'Kitchen',
      'TV',
    ],
  ),
  Homestay(
    id: '6',
    name: 'Luxury City Center Homestay',
    rating: 4.7,
    reviews: 250,
    location: cityList[12],
    description: 'Stay in the heart of the city in this luxury homestay with modern amenities and stunning skyline views.',
    thumbnail: ImgApi.photo[56],
    price: 250,
    discount: 25,
    type: 'Villa',
    capacity: 10,
    facilities: [
      'Free Wi-Fi',
    ],
  ),
  Homestay(
    id: '7',
    name: 'Modern Urban Homestay',
    rating: 4.3,
    reviews: 110,
    location: cityList[13],
    description: 'Stay in the heart of the city at our modern urban homestay, designed for comfort and convenience.',
    thumbnail: ImgApi.photo[97],
    price: 220,
    discount: 18,
    capacity: 5,
    facilities: [
      'Kitchen',
    ],
  ),
  Homestay(
    id: '8',
    name: 'Charming Boutique Homestay',
    rating: 4.6,
    reviews: 90,
    location: cityList[13],
    description: 'Experience the charm of Paris at our boutique homestay, where elegance meets comfort.',
    thumbnail: ImgApi.photo[70],
    price: 180,
    discount: 15,
    type: 'Apartment',
    capacity: 8,
    facilities: [
      'Free Wi-Fi',
      'Kitchen',
      'TV',
      'Swimming Pool',
      'Air Conditioning',
      'Parking',
    ],
  ),
  Homestay(
    id: '9',
    name: 'Luxury City Center Homestay',
    rating: 4.7,
    reviews: 150,
    location: cityList[13],
    description: 'Indulge in luxury at our city center homestay, offering stunning views and top-notch amenities.',
    thumbnail: ImgApi.photo[59],
    price: 200,
    discount: 20,
    type: 'Villa',
    capacity: 10,
    facilities: [
      'Free Wi-Fi',
      'Kitchen',
      'TV',
      'Swimming Pool',
      'Air Conditioning',
      'Parking',
    ],
  ),
  Homestay(
    id: '10',
    name: 'Cozy Mountain Lodge',
    rating: 4.6,
    reviews: 90,
    location: cityList[14],
    description: 'Escape to the mountains at our cozy lodge, perfect for winter sports enthusiasts and nature lovers.',
    thumbnail: ImgApi.photo[60],
    price: 250,
    discount: 5,
    type: 'Cabin',
    capacity: 5,
    facilities: [
      'Free Wi-Fi',
      'TV',
      'Swimming Pool',
      'Air Conditioning',
      'Parking',
    ],
  ),
  Homestay(
    id: '11',
    name: 'Modern Urban Homestay',
    rating: 4.3,
    reviews: 110,
    location: cityList[14],
    description: 'Stay in the heart of the city at our modern urban homestay, designed for comfort and convenience.',
    thumbnail: ImgApi.photo[61],
    price: 220,
    discount: 15,
    type: 'Apartment',
    capacity: 6,
    facilities: [
      'TV',
      'Swimming Pool',
      'Air Conditioning',
      'Parking',
    ],
  ),
  Homestay(
    id: '12',
    name: 'Charming Boutique Homestay',
    rating: 4.8,
    reviews: 200,
    location: cityList[14],
    description: 'Experience the charm of Paris at our boutique homestay, where elegance meets comfort.',
    thumbnail: ImgApi.photo[62],
    price: 180,
    discount: 15,
    type: 'Cabin',
    capacity: 5,
    facilities: [
      'Free Wi-Fi',
      'Kitchen',
      'TV',
      'Swimming Pool',
      'Air Conditioning',
      'Parking',
    ],
  ),
  Homestay(
    id: '13',
    name: 'Luxury City Center Homestay',
    rating: 4.7,
    reviews: 150,
    location: cityList[15],
    description: 'Indulge in luxury at our city center homestay, offering stunning views and top-notch amenities.',
    thumbnail: ImgApi.photo[63],
    price: 200,
    discount: 20,
    type: 'Villa',
    capacity: 10,
    facilities: [
      'Free Wi-Fi',
      'Kitchen',
      'TV',
      'Swimming Pool',
      'Air Conditioning',
      'Parking',
    ],
  ),
  Homestay(
    id: '14',
    name: 'Cozy Mountain Lodge',
    rating: 4.6,
    reviews: 90,
    location: cityList[15],
    description: 'Escape to the mountains at our cozy lodge, perfect for winter sports enthusiasts and nature lovers.',
    thumbnail: ImgApi.photo[64],
    price: 250,
    type: 'Cabin',
    discount: 25,
    capacity: 4,
    facilities: [
      'Free Wi-Fi',
      'Parking',
    ],
  ),
  Homestay(
    id: '15',
    name: 'Modern Urban Homestay',
    rating: 4.3,
    reviews: 110,
    location: cityList[16],
    description: 'Stay in the heart of the city at our modern urban homestay, designed for comfort and convenience.',
    thumbnail: ImgApi.photo[65],
    price: 220,
    discount: 15,
    type: 'Cabin',
    capacity: 4,
    facilities: [
      'Free Wi-Fi',
      'Swimming Pool',
      'Air Conditioning',
      'Parking',
    ],
  ),
  Homestay(
    id: '16',
    name: 'Charming Boutique',
    rating: 4.8,
    reviews: 200,
    location: cityList[16],
    description: 'Experience the charm of Paris at our boutique homestay, where elegance meets comfort.',
    thumbnail: ImgApi.photo[66],
    price: 180,
    discount: 15,
    capacity: 15,
    facilities: [
      'Free Wi-Fi',
      'Kitchen',
      'TV',
      'Air Conditioning',
    ],
  ),
  Homestay(
    id: '17',
    name: 'Luxury City Center Homestay',
    rating: 4.7,
    reviews: 150,
    location: cityList[16],
    description: 'Indulge in luxury at our city center homestay, offering stunning views and top-notch amenities.',
    thumbnail: ImgApi.photo[67],
    price: 200,
    discount: 20,
    capacity: 10,
    facilities: [
      'Kitchen',
      'Swimming Pool',
      'Air Conditioning',
      'Parking',
    ],
  ),
  Homestay(
    id: '18',
    name: 'Cozy Mountain Lodge',
    rating: 4.6,
    reviews: 90,
    location: cityList[17],
    description: 'Escape to the mountains at our cozy lodge, perfect for winter sports enthusiasts and nature lovers.',
    thumbnail: ImgApi.photo[68],
    price: 250,
    discount: 25,
    capacity: 15,
    facilities: [
      'Free Wi-Fi',
      'Kitchen',
      'TV',
      'Swimming Pool',
      'Air Conditioning',
      'Parking',
    ],
  ),
  Homestay(
    id: '19',
    name: 'Modern Urban Homestay',
    rating: 4.3,
    reviews: 110,
    location: cityList[18],
    description: 'Stay in the heart of the city at our modern urban homestay, designed for comfort and convenience.',
    thumbnail: ImgApi.photo[69],
    price: 220,
    discount: 15,
    capacity: 10,
    facilities: [
      'Free Wi-Fi',
      'Kitchen',
      'TV',
      'Air Conditioning',
    ],
  ),  
  Homestay(
    id: '20',
    name: 'Charming Boutique Homestay',
    rating: 4.8,
    reviews: 200,
    location: cityList[18],
    description: 'Experience the charm of Paris at our boutique homestay, where elegance meets comfort.',
    thumbnail: ImgApi.photo[70],
    price: 180,
    discount: 15,
    type: 'Apartment',
    capacity: 6,
    facilities: [
      'Free Wi-Fi',
      'Kitchen',
      'TV',
      'Swimming Pool',
      'Air Conditioning',
      'Parking',
    ],
  )
];