import 'package:booking_app/constants/img_api.dart';
import 'package:booking_app/models/city.dart';

class Hotel {
  final String id;
  final String name;
  final double rating;
  final double reviews;
  final City location;
  final String description;
  final String thumbnail;
  final double price;
  final int stars;
  final double discount;
  final List<String>? facilities;

  Hotel({
    required this.id,
    required this.name,
    this.rating = 0,
    this.reviews = 0,
    required this.location,
    required this.description,
    required this.thumbnail,
    required this.price,
    this.discount = 0,
    this.stars = 4,
    this.facilities
  });

  String get formattedPrice => '\$${price.toStringAsFixed(2)}';
}

final List<Hotel> hotelList = [
  Hotel(
    id: '1',
    name: 'Azure Haven Hotel',
    rating: 4.5,
    reviews: 120,
    location: cityList[10],
    description: 'Nestled along the pristine coastline, Sunset Tide Resort offers breathtaking ocean views and luxurious amenities perfect for a relaxing escape. Guests',
    thumbnail: ImgApi.photo[10],
    price: 150,
    discount: 10,
    stars: 5,
    facilities: [
      'Free Wi-Fi',
      'Swimming Pool',
      'Spa & Wellness Center',
      'Restaurant',
      'Fitness Center',
    ],
  ),
  Hotel(
    id: '2',
    name: 'Urban Business Hotel Example',
    rating: 4.0,
    reviews: 80,
    location: cityList[16],
    description: 'The Urban Retreat is a contemporary hotel designed for both business and leisure travelers.',
    thumbnail: ImgApi.photo[2],
    price: 120,
    discount: 5,
    facilities: [
      'Spa & Wellness Center',
      'Restaurant',
      'Fitness Center',
    ],
  ),
  Hotel(
    id: '3',
    name: 'Charming Boutique Hotel',
    rating: 4.8,
    reviews: 200,
    location: cityList[15],
    description: 'Experience the charm of Paris at our boutique hotel, where elegance meets comfort.',
    thumbnail: ImgApi.photo[16],
    price: 180,
    discount: 15,
    facilities: [
      'Free Wi-Fi',
      'Spa & Wellness Center',
    ],
  ),
  Hotel(
    id: '4',
    name: 'Luxury City Center Hotel',
    rating: 4.7,
    reviews: 150,
    location: cityList[14],
    description: 'Indulge in luxury at our city center hotel, offering stunning views and top-notch amenities.',
    thumbnail: ImgApi.photo[7],
    price: 200,
    discount: 20,
    facilities: [
      'Free Wi-Fi',
      'Swimming Pool',
      'Spa & Wellness Center',
      'Restaurant',
      'Fitness Center',
    ],
  ),
  Hotel(
    id: '5',
    name: 'Cozy Mountain Lodge',
    rating: 4.6,
    reviews: 90,
    location: cityList[10],
    description: 'Escape to the mountains at our cozy lodge, perfect for winter sports enthusiasts and nature lovers.',
    thumbnail: ImgApi.photo[5],
    price: 250,
    discount: 25,
    facilities: [
      'Free Wi-Fi',
      'Swimming Pool',
    ],
  ),
  Hotel(
    id: '6',
    name: 'Modern Urban Hotel',
    rating: 4.3,
    reviews: 110,
    location: cityList[14],
    description: 'Stay in the heart of the city at our modern urban hotel, designed for comfort and convenience.',
    thumbnail: ImgApi.photo[24],
    price: 220,
    discount: 15,
    facilities: [
      'Free Wi-Fi',
      'Swimming Pool',
      'Spa & Wellness Center',
      'Restaurant',
      'Fitness Center',
    ],
  ),
  Hotel(
    id: '7',
    name: 'Desert Oasis Resort',
    rating: 4.9,
    reviews: 130,
    location: cityList[13],
    description: 'Relax and unwind at our desert oasis resort, featuring luxurious amenities and stunning desert views.',
    thumbnail: ImgApi.photo[14],
    price: 300,
    discount: 30,
    facilities: [
      'Free Wi-Fi',
      'Spa & Wellness Center',
      'Restaurant',
      'Fitness Center',
    ],
  ),
  Hotel(
    id: '8',
    name: 'Cultural Heritage Hotel',
    rating: 4.4,
    reviews: 70,
    location: cityList[12],
    description: 'Immerse yourself in culture at our heritage hotel, showcasing the rich history of Casablanca.',
    thumbnail: ImgApi.photo[8],
    price: 160,
    discount: 10,
    facilities: [
      'Free Wi-Fi',
      'Fitness Center',
    ],
  ),
  Hotel(
    id: '9',
    name: 'Tropical Paradise Resort',
    rating: 4.2,
    reviews: 140,
    location: cityList[12],
    description: 'Experience paradise at our tropical resort, surrounded by lush gardens and pristine beaches.',
    thumbnail: ImgApi.photo[9],
    price: 280,
    discount: 20,
    facilities: [
      'Free Wi-Fi',
      'Swimming Pool',
      'Spa & Wellness Center',
      'Restaurant',
      'Fitness Center',
    ],
  ),
  Hotel(
    id: '10',
    name: 'Cultural Heritage Hotel',
    rating: 4.4,
    reviews: 70,
    location: cityList[16],
    description: 'Immerse yourself in culture at our heritage hotel, showcasing the rich history of Beijing.',
    thumbnail: ImgApi.photo[1],
    price: 160,
    stars: 5,
    discount: 10,
    facilities: [
      'Swimming Pool',
      'Spa & Wellness Center',
      'Fitness Center',
    ],
  ),
  Hotel(
    id: '11',
    name: 'Luxury Beachfront Resort',
    rating: 4.9,
    reviews: 150,
    location: cityList[10],
    description: 'Relax in luxury at our beachfront resort, offering stunning ocean views and top-notch amenities.',
    thumbnail: ImgApi.photo[11],
    price: 350,
    discount: 30,
    facilities: [
      'Free Wi-Fi',
      'Swimming Pool',
      'Spa & Wellness Center',
      'Restaurant',
      'Fitness Center',
    ],
  ),
  Hotel(
    id: '12',
    name: 'Charming Countryside Inn',
    rating: 4.6,
    reviews: 90,
    location: cityList[19],
    description: 'Experience the charm of the countryside at our inn, surrounded by beautiful landscapes.',
    thumbnail: ImgApi.photo[12],
    price: 140,
    discount: 15,
    facilities: [
      'Free Wi-Fi',
      'Swimming Pool',
      'Spa & Wellness Center',
    ],
  ),
  Hotel(
    id: '13',
    name: 'Elegant City Hotel',
    rating: 4.5,
    reviews: 120,
    location: cityList[11],
    description: 'Stay in style at our elegant city hotel, offering modern amenities and a prime location.',
    thumbnail: ImgApi.photo[13],
    price: 190,
    discount: 20,
    facilities: [
      'Free Wi-Fi',
      'Swimming Pool',
      'Spa & Wellness Center',
      'Restaurant',
      'Fitness Center',
    ],
  ),
  Hotel(
    id: '14',
    name: 'Seaside Resort',
    rating: 4.7,
    reviews: 130,
    location: cityList[11],
    description: 'Enjoy the sun and sea at our seaside resort, featuring luxurious accommodations and stunning views.',
    thumbnail: ImgApi.photo[4],
    price: 220,
    discount: 25,
    facilities: [
      'Free Wi-Fi',
      'Swimming Pool',
      'Spa & Wellness Center',
      'Restaurant',
    ],
  ),
  Hotel(
    id: '15',
    name: 'Mountain Retreat Hotel',
    rating: 4.8,
    reviews: 110,
    location: cityList[18],
    description: 'Escape to the mountains at our retreat hotel, perfect for outdoor enthusiasts and nature lovers.',
    thumbnail: ImgApi.photo[15],
    price: 260,
    stars: 5,
    discount: 20,
    facilities: [
      'Free Wi-Fi',
      'Spa & Wellness Center',
      'Fitness Center',
    ],
  ),
  Hotel(
    id: '16',
    name: 'Luxury Spa Resort',
    rating: 4.9,
    reviews: 140,
    location: cityList[11],
    description: 'Relax and rejuvenate at our luxury spa resort, offering world-class treatments and stunning views.',
    thumbnail: ImgApi.photo[16],
    price: 400,
    discount: 35,
    facilities: [
      'Free Wi-Fi',
      'Swimming Pool',
      'Spa & Wellness Center',
      'Restaurant',
      'Fitness Center',
    ],
  ),
  Hotel(
    id: '17',
    name: 'Historic Castle Hotel',
    rating: 4.3,
    reviews: 80,
    location: cityList[18],
    description: 'Experience history at our castle hotel, where luxury meets heritage.',
    thumbnail: ImgApi.photo[17],
    price: 300,
    discount: 15,
    facilities: [
      'Free Wi-Fi',
      'Swimming Pool',
      'Spa & Wellness Center',
      'Restaurant',
      'Fitness Center',
    ],
  ),
  Hotel(
    id: '18',
    name: 'Eco-Friendly Resort',
    rating: 4.6,
    reviews: 100,
    location: cityList[11],
    description: 'Stay green at our eco-friendly resort, surrounded by nature and designed for sustainability.',
    thumbnail: ImgApi.photo[18],
    price: 180,
    discount: 20,
    facilities: [
      'Free Wi-Fi',
      'Restaurant',
    ],
  ),
  Hotel(
    id: '19',
    name: 'Artistic Boutique Hotel',
    rating: 4.4,
    reviews: 90,
    location: cityList[19],
    description: 'Immerse yourself in art and culture at our boutique hotel, featuring unique designs and local art.',
    thumbnail: ImgApi.photo[20],
    price: 170,
    discount: 10,
    stars: 3,
    facilities: [
      'Free Wi-Fi',
      'Swimming Pool',
      'Spa & Wellness Center',
      'Fitness Center',
    ],
  ),
  Hotel(
    id: '20',
    name: 'Luxury Safari Lodge',
    rating: 4.8,
    reviews: 130,
    location: cityList[19],
    description: 'Experience the wild at our luxury safari lodge, offering unforgettable wildlife experiences and stunning views.',
    thumbnail: ImgApi.photo[19],
    price: 500,
    discount: 40,
    stars: 3,
    facilities: [
      'Free Wi-Fi',
      'Swimming Pool',
      'Spa & Wellness Center',
      'Restaurant',
      'Fitness Center',
    ],
  ),
];