import 'package:booking_app/constants/img_api.dart';
import 'package:booking_app/models/city.dart';

class Workspace {
  final String id;
  final String name;
  final double rating;
  final double reviews;
  final City location;
  final String description;
  final String thumbnail;
  final double price;
  final String? website;
  final List<String>? facilities;
  final List<String> type;

  Workspace({
    required this.id,
    required this.name,
    this.rating = 0,
    this.reviews = 0,
    required this.location,
    required this.description,
    required this.thumbnail,
    required this.price,
    this.website,
    this.facilities,
    this.type = const ['Private Office', 'Shared Workspace', 'Dedicated Desk', 'Conference Room', 'Event']
  });
  String get formattedPrice => '\$${price.toStringAsFixed(2)}';
  String get formattedDiscount => '\$${price.toStringAsFixed(2)}';
}

final List<Workspace> workspaceList = [
  Workspace(
    id: '1',
    name: 'Azure Workspace',
    rating: 4.5,
    reviews: 120,
    location: cityList[10],
    description: 'Nestled along the pristine coastline, Sunset Tide Resort offers breathtaking ocean views and luxurious amenities perfect for a relaxing escape. Guests',
    thumbnail: ImgApi.photo[101],
    price: 150,
    website: 'https://example.com',
    type: ['Private Office', 'Dedicated Desk', 'Conference Room', 'Event'],
    facilities: [
      'Coffee & Tea',
      'Meeting Rooms',
    ],
  ),
  Workspace(
    id: '2',
    name: 'Urban Business Workspace',
    rating: 4.0,
    reviews: 80,
    location: cityList[10],
    description: 'The Urban Retreat is a contemporary hotel designed for both business and leisure travelers.',
    thumbnail: ImgApi.photo[112],
    price: 120,
    type: ['Private Office', 'Shared Workspace', 'Dedicated Desk', 'Conference Room',],
    facilities: [
      'Coffee & Tea',
      'Snack & Drinks',
      'Parking',
    ],
  ),
  Workspace(
    id: '3',
    name: 'Cozy Mountain Retreat',
    rating: 4.2,
    reviews: 95,
    location: cityList[11],
    description: 'A serene escape in the mountains, perfect for nature lovers and adventure seekers.',
    thumbnail: ImgApi.photo[103],
    price: 130,
    type: ['Dedicated Desk', 'Conference Room', 'Event'],
    facilities: [
      'Coffee & Tea',
      'VIP Room',
    ],
  ),
  Workspace(
    id: '4',
    name: 'Modern Urban Workspace',
    rating: 4.8,
    reviews: 150,
    location: cityList[11],
    description: 'A vibrant Workspace space in the heart of the city, ideal for startups and freelancers.',
    thumbnail: ImgApi.photo[114],
    price: 140,
    type: ['Dedicated Desk'],
    facilities: [
      'Coffee & Tea',
      'VIP Room',
    ],
  ),
  Workspace(
    id: '5',
    name: 'Tranquil Nature Retreat',
    rating: 4.6,
    reviews: 110,
    location: cityList[11],
    description: 'A peaceful retreat surrounded by nature, perfect for relaxation and creativity.',
    thumbnail: ImgApi.photo[105],
    price: 160,
    type: ['Private Office', 'Shared Workspace'],
    facilities: [
      'Coffee & Tea',
      'VIP Rooms',
      'Parking',
    ],
  ),
  Workspace(
    id: '6',
    name: 'Luxury City Center Workspace',
    rating: 4.7,
    reviews: 200,
    location: cityList[12],
    description: 'A premium Workspace space with stunning skyline views and top-notch amenities.',
    thumbnail: ImgApi.photo[116],
    price: 180,
    facilities: [
      'Coffee & Tea',
      'VIP Rooms',
      'Parking',
    ],
  ),
  Workspace(
    id: '7',
    name: 'Charming Boutique Workspace',
    rating: 4.3,
    reviews: 90,
    location: cityList[12],
    description: 'A cozy and stylish Workspace space with a unique atmosphere.',
    thumbnail: ImgApi.photo[107],
    price: 110,
    facilities: [
      'Coffee & Tea',
      'Meeting Rooms',
      'Parking',
    ],
  ),
  Workspace(
    id: '8',
    name: 'Elegant Urban Workspace',
    rating: 4.4,
    reviews: 130,
    location: cityList[13],
    description: 'A sophisticated Workspace space designed for professionals and entrepreneurs.',
    thumbnail: ImgApi.photo[118],
    type: ['Private Office', 'Conference Room', 'Event'],
    price: 170,
    facilities: [
      'Coffee & Tea',
      'VIP Rooms',
      'Parking',
    ],
  ),
  Workspace(
    id: '9',
    name: 'Cozy Mountain Lodge',
    rating: 4.6,
    reviews: 90,
    location: cityList[13],
    description: 'Escape to the mountains at our cozy lodge, perfect for winter sports enthusiasts and nature lovers.',
    thumbnail: ImgApi.photo[109],
    price: 250,
    facilities: [
      'Coffee & Tea',
      'Snack & Drinks',
      'Meeting Rooms',
      'Parking',
    ],
  ),
  Workspace(
    id: '10',
    name: 'Charming Boutique Workspace',
    rating: 4.6,
    reviews: 90,
    location: cityList[13],
    description: 'Experience the charm of Paris at our boutique Workspace space, where elegance meets comfort.',
    thumbnail: ImgApi.photo[120],
    price: 180,
    type: ['Private Office', 'Shared Workspace'],
    facilities: [
      'Coffee & Tea',
    ],
  ),
  Workspace(
    id: '11',
    name: 'Modern Urban Workspace',
    rating: 4.3,
    reviews: 110,
    location: cityList[13],
    description: 'Stay in the heart of the city at our modern urban Workspace space, designed for comfort and convenience.',
    thumbnail: ImgApi.photo[111],
    price: 220,
    type: ['Private Office'],
    facilities: [
      'Coffee & Tea',
      'Gaming Rooms',
      'Bilyard Room',
      'Parking',
    ],
  ),
  Workspace(
    id: '12',
    name: 'Luxury City Center Workspace',
    rating: 4.7,
    reviews: 150,
    location: cityList[14],
    description: 'Indulge in luxury at our city center Workspace space, offering stunning views and top-notch amenities.',
    thumbnail: ImgApi.photo[102],
    price: 200,
    facilities: [
      'Coffee & Tea',
      'Meeting Rooms',
      'Parking',
    ],
  ),
  Workspace(
    id: '13',
    name: 'Cozy Mountain Lodge',
    rating: 4.6,
    reviews: 90,
    location: cityList[15],
    description: 'Escape to the mountains at our cozy lodge, perfect for winter sports enthusiasts and nature lovers.',
    thumbnail: ImgApi.photo[113],
    price: 250,
    facilities: [
      'Coffee & Tea',
      'Library',
    ],
  ),
  Workspace(
    id: '14',
    name: 'Modern Urban Workspace',
    rating: 4.3,
    reviews: 110,
    location: cityList[15],
    description: 'Stay in the heart of the city at our modern urban Workspace space, designed for comfort and convenience.',
    thumbnail: ImgApi.photo[104],
    type: ['Dedicated Desk', 'Conference Room', 'Event'],
    price: 220,
    facilities: [
      'Coffee & Tea',
      'VIP Rooms',
      'Parking',
    ],
  ),
  Workspace(
    id: '15',
    name: 'Charming Boutique Workspace',
    rating: 4.8,
    reviews: 200,
    location: cityList[16],
    description: 'Experience the charm of Paris at our boutique Workspace space, where elegance meets comfort.',
    thumbnail: ImgApi.photo[115],
    price: 180,
    facilities: [
      'Coffee & Tea',
      'Snack & Drinks',
      'Meeting Rooms',
      'Parking',
    ],
  ),
  Workspace(
    id: '16',
    name: 'Luxury City Center Workspace',
    rating: 4.7,
    reviews: 150,
    location: cityList[16],
    description: 'Indulge in luxury at our city center Workspace space, offering stunning views and top-notch amenities.',
    thumbnail: ImgApi.photo[106],
    type: ['Private Office', 'Shared Workspace', 'Event'],
    price: 200,
    facilities: [
      'Coffee & Tea',
      'VIP Rooms',
      'Parking',
    ],
  ),
  Workspace(
    id: '17',
    name: 'Cozy Mountain Lodge',
    rating: 4.6,
    reviews: 90,
    location: cityList[17],
    description: 'Escape to the mountains at our cozy lodge, perfect for winter sports enthusiasts and nature lovers.',
    thumbnail: ImgApi.photo[134],
    price: 250,
    type: ['Shared Workspace', 'Dedicated Desk', 'Conference Room', 'Event'],
    facilities: [
      'Meeting Rooms',
      'Parking',
    ],
  ),
  Workspace(
    id: '18',
    name: 'Modern Urban Workspace',
    rating: 4.3,
    reviews: 110,
    location: cityList[17],
    description: 'Stay in the heart of the city at our modern urban Workspace space, designed for comfort and convenience.',
    thumbnail: ImgApi.photo[114],
    price: 220,
    type: ['Private Office', 'Shared Workspace', 'Event'],
    facilities: [
      'Coffee & Tea',
      'Snack & Drinks',
      'Meeting Rooms',
      'Parking',
    ],
  ),
  Workspace(
    id: '19',
    name: 'Luxury City Center Workspace',
    rating: 4.7,
    reviews: 150,
    location: cityList[18],
    description: 'Indulge in luxury at our city center Workspace space, offering stunning views and top-notch amenities.',
    thumbnail: ImgApi.photo[120],
    price: 200,
    facilities: [
      'Coffee & Tea',
      'Snack & Drinks',
      'VIP Rooms',
      'Parking',
    ],
  ),
  Workspace(
    id: '20',
    name: 'Charming Boutique Workspace',
    rating: 4.8,
    reviews: 200,
    location: cityList[19],
    description: 'Experience the charm of Paris at our boutique Workspace space, where elegance meets comfort.',
    thumbnail: ImgApi.photo[125],
    price: 180,
    type: ['Private Office', 'Shared Workspace', 'Dedicated Desk', 'Conference Room'],
    facilities: [
      'Coffee & Tea',
      'Snack & Drinks',
      'Meeting Rooms',
      'Parking',
    ],
  ),
];